# Generated by Django 4.2.4 on 2023-10-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="workouts",
            field=models.ManyToManyField(to="workout_users.workout"),
        ),
    ]
