# Generated by Django 4.2.4 on 2023-10-09 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0002_alter_user_workouts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.URLField()),
                ("caption", models.TextField(max_length=200)),
                ("likes", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="workout",
            name="exercises",
        ),
        migrations.RemoveField(
            model_name="user",
            name="height",
        ),
        migrations.RemoveField(
            model_name="user",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="user",
            name="workouts",
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="Set",
        ),
        migrations.DeleteModel(
            name="Workout",
        ),
        migrations.AddField(
            model_name="post",
            name="poster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="posts",
            field=models.ManyToManyField(to="workout_users.post"),
        ),
    ]
