# Generated by Django 4.2.4 on 2023-10-12 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0005_comment_post_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likers",
            field=models.ManyToManyField(
                related_name="liked_post", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="poster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
