# Generated by Django 4.2.4 on 2023-10-13 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0007_user_followers_user_followings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                null=True, related_name="follower", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followings",
            field=models.ManyToManyField(
                null=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
