# Generated by Django 4.2.4 on 2023-10-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0008_alter_user_followers_alter_user_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.URLField(
                default="https://static.wikia.nocookie.net/d92f8304-34eb-4769-b050-47c68421cd9b/scale-to-width/370"
            ),
        ),
    ]
