# Generated by Django 4.2.4 on 2023-10-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0009_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.URLField(
                default="https://centerforgreatapes.org/wp-content/uploads/2021/03/IMG_00251_Louie.jpg"
            ),
        ),
    ]
