# Generated by Django 4.2.4 on 2023-10-13 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0011_comment_timestamp_post_timestamp_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="users",
        ),
        migrations.RemoveField(
            model_name="message",
            name="recipients",
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
