# Generated by Django 4.2.4 on 2023-10-13 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workout_users",
            "0012_remove_conversation_users_remove_message_recipients_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="users",
            field=models.ManyToManyField(
                related_name="conversation_members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
