# Generated by Django 4.2.4 on 2023-10-13 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0014_remove_conversation_users_conversation_recipient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="recipient",
        ),
        migrations.AddField(
            model_name="conversation",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
