# Generated by Django 4.2.4 on 2023-10-26 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0015_remove_conversation_recipient_conversation_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="messages",
            field=models.ManyToManyField(null=True, to="workout_users.message"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="users",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(upload_to="post_images/"),
        ),
    ]
