# Generated by Django 4.2.6 on 2023-10-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workout_users",
            "0016_alter_conversation_messages_alter_conversation_users_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.URLField(max_length=10000),
        ),
    ]
