# Generated by Django 4.2.6 on 2023-11-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0017_alter_post_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(max_length=10000, upload_to=""),
        ),
    ]
