# Generated by Django 4.2.6 on 2023-11-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_users", "0019_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                default="default-pfp.webp", max_length=10000, upload_to=""
            ),
        ),
    ]
